<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="HandlingContainer" Id="{c56ebb4c-ceb3-40f9-bf3b-b69637f91515}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK HandlingContainer EXTENDS ZCore.ObjectContainer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
  {attribute 'hide'}
  _parent : REFERENCE TO HandlingUnit;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_init" Id="{c8cceac7-f10c-45f1-b86d-41e565451fef}">
      <Declaration><![CDATA[{attribute 'hide' }
METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
  unit : REFERENCE TO HandlingUnit;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_parent REF= unit;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>