<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MoverSequenceBoot" Id="{d78054fc-4c36-4deb-9fc6-a2bd47a74319}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MoverSequenceBoot EXTENDS MoverSequence IMPLEMENTS ZCore.ISequence
VAR
  _step : ZCore.Step(MoverStep.BootBegin, MoverStep.BootEnd);
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF OnStart(_step) THEN
  ; // init custom sequence variables here ...
END_IF

REPEAT
  LogStep();

  CASE _step.Index OF
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
    MoverStep.BootBegin:
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
      IF _step.OnEntry()
      THEN
        // initialize equipment
        _io();
        _actuator();
        _collision();
        _fieldbus();
        _axis();
        _unit();
      END_IF
      
      _parent._objectManager.Cyclic();      
      Assert(_parent._objectManager);
      IF _parent._objectManager.Booted
      THEN
        _step.SetNext(MoverStep.BootEnd);
      END_IF

    (* -------------------------------------------------------------------------------------------------------------------------------- *)
    MoverStep.BootEnd:
    (* -------------------------------------------------------------------------------------------------------------------------------- *)
      SetBusy(FALSE);
      
  ELSE
    Abort('sequence contains unhandled step');
  END_CASE
UNTIL _step.IsNotRepeatable() OR_ELSE NOT Busy END_REPEAT]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>